#!/usr/bin/env php
<?php
include 'Core/init.php';
define('APP_CONTROLLER', APP_ROOT . DIRECTORY_SEPARATOR . 'Core' . DIRECTORY_SEPARATOR . 'App' . DIRECTORY_SEPARATOR . 'Controller' . DIRECTORY_SEPARATOR);
define('APP_MODEL', APP_ROOT . DIRECTORY_SEPARATOR . 'Core' . DIRECTORY_SEPARATOR . 'App' . DIRECTORY_SEPARATOR . 'Model' . DIRECTORY_SEPARATOR);
define('APP_VIEW', APP_ROOT . DIRECTORY_SEPARATOR . 'Core' . DIRECTORY_SEPARATOR . 'App' . DIRECTORY_SEPARATOR . 'View' . DIRECTORY_SEPARATOR . 'Content' . DIRECTORY_SEPARATOR);
define('APP_FACTORY', APP_ROOT . DIRECTORY_SEPARATOR . 'Factory' . DIRECTORY_SEPARATOR);

$shortopts = '';
$shortopts .= 'f:';
$shortopts .= 'q';
$shortopts .= 'd';
$shortopts .= 'g';
$shortopts .= 'p';
$shortopts .= 'ag';
$shortopts .= 'ap';
$shortopts .= 'c';
$shortopts .= 'v';
$shortopts .= 'h';

$longopts = array(
    "FILENAME:",
    "QUERY",
    "DYNAMIC",
    "GET",
    "POST",
    "AJAXGET",
    "AJAXPOST",
    "CRUD",
    "VIEW",
    "HELP"
);
$options = getopt($shortopts, $longopts);

function main($options) {
    if (isset($options['HELP'])) {
        if ($options['HELP'] === false) {
            help();
        }
    } else {
        if (isset($options['h'])) {
            help();
        } else {
            if ((isset($options['f']) && !empty($options['f'])) or (isset($options['FILENAME']) && !empty($options['FILENAME']))) {
                $route = $options['f'] ?? $options['FILENAME'] ?? null;
                $query = ($options['q'] ?? $options['QUERY'] ?? true) === false;
                $dynamic = ($options['d'] ?? $options['DYNAMIC'] ?? true) === false;
                $get = ($options['g'] ?? $options['GET'] ?? true) === false;
                $post = ($options['p'] ?? $options['POST'] ?? true) === false;
                $getajax = ($options['ag'] ?? $options['AJAXGET'] ?? true) === false;
                $postajax = ($options['ap'] ?? $options['AJAXPOST'] ?? true) === false;
                $crud = ($options['c'] ?? $options['CRUD'] ?? true) === false;
                $view = ($options['v'] ?? $options['VIEW'] ?? true) === false;

                $fetchControllerCode = buildController($route, $dynamic, $get, $post, $getajax, $postajax);
                $fetchModelCode = buildModel($route, $query, $dynamic, $crud);

                $filenameController = APP_CONTROLLER . ucfirst($route) . '.class.php';
                $filenameModel = APP_MODEL . ucfirst($route) . 'Model.class.php';
                $filenameView = APP_VIEW . $route . '.tpl.php';
                if (file_exists($filenameController) OR file_exists($filenameModel)) {
                    echo 'Controlador y/o Modelo para esa ruta/función ya existe' . PHP_EOL;
                } else {
                    if ($view == true) {
                        touch($filenameView);
                    }
                    file_put_contents($filenameController, $fetchControllerCode);
                    file_put_contents($filenameModel, $fetchModelCode);
                }
            }
        }
    }
}

function help() {
    echo '
        PHP Absurdly Lite Framework (ALF) MVC Factory
        Uso:
            build [OPCIÓN...]
        
        Opciones de ayuda:
        -h, --HELP                      Mostrar opciones de ayuda

        Opciones de la aplicación:
        -f,  --FILENAME [nombre...]            Nombre de Ruta/Función para crear Controller y Model
        -q,  --QUERY                           Model: Agrega Función para manejo de Query Strings al Model
        -d,  --DYNAMIC                         Controller y Model: Presente si Ruta/Función es dinámica
        -g,  --GET                             Controller: Añade GET
        -p,  --POST                            Controller: Añade POST
        -ag, --AJAXGET                         Controller: Añade GET AJAX
        -ap, --AJAXPOST                        Controller: Añade POST AJAX
        -c,  --CRUD                            Model: Añade CRUD al Model
        -v,  --VIEW                            Vista: Añade una vista a Ruta
        ' . PHP_EOL;
}

function buildModel($route, $query, $dynamic, $crud) {
    $layoutModel = layoutModel();

    $temp = '
    // private function setPropiedad() {
    //    $data = $this->getPropiedad();
    //    $this->propiedad = $data;
    // }';
    $queryTemplate = $query === true ? queryModelTemplate() : '';
    $dynamicTemplate = $dynamic === true ? dynamicModelTemplate() : staticModelTemplate();
    $setterTemplate = $dynamic === true ? setterModelTemplate() : $temp;

    $crudTemplate = $crud === true ? crudModelTemplate() : '';

    $templates = [ucfirst($route), $dynamicTemplate, $setterTemplate, $crudTemplate, $queryTemplate];
    $markup = ['{{filename}}', '{{dynamic}}', '{{setters}}', '{{crud}}', '{{query}}'];

    return '<?php' . PHP_EOL . str_replace($markup, $templates, $layoutModel);
}

function buildController($route, $dynamic, $get, $post, $getajax, $postajax) {
    $layoutController = layoutController();

    $dynamicTemplate = $dynamic === true ? dynamicControllerTemplate() : staticControllerTemplate();
    $getTemplate = $get === true ? getControllerTemplate() : '';
    $postTemplate = $post === true ? postControllerTemplate() : '';
    $getajaxTemplate = $getajax === true ? getajaxControllerTemplate(ucfirst($route)) : '';
    $postajaxTemplate = $postajax === true ? postajaxControllerTemplate(ucfirst($route)) : '';

    $templates = [ucfirst($route), $getTemplate, $postTemplate, $getajaxTemplate, $postajaxTemplate, $dynamicTemplate];
    $markup = ['{{filename}}', '{{get}}', '{{post}}', '{{getajax}}', '{{postajax}}', '{{values}}'];

    return '<?php' . PHP_EOL . str_replace($markup, $templates, $layoutController);
}

// Model
function layoutModel() {
    ob_start();
    include_once APP_FACTORY . 'model.txt';
    return ob_get_clean();
}
function staticModelTemplate() {
    ob_start();
    include_once APP_FACTORY . 'staticprops.txt';
    return ob_get_clean();
}
function dynamicModelTemplate() {
    ob_start();
    include_once APP_FACTORY . 'dynamicprops.txt';
    return ob_get_clean();
}
function queryModelTemplate() {
    ob_start();
    include_once APP_FACTORY . 'query.txt';
    return ob_get_clean();
}
function setterModelTemplate() {
    ob_start();
    include_once APP_FACTORY . 'setters.txt';
    return ob_get_clean();
}
function crudModelTemplate() {
    ob_start();
    include_once APP_FACTORY . 'crud.txt';
    return ob_get_clean();
}

// Controller
function layoutController() {
    ob_start();
    include_once APP_FACTORY . 'controller.txt';
    return ob_get_clean();
}
function staticControllerTemplate() {
    ob_start();
    include_once APP_FACTORY . 'static.txt';
    return ob_get_clean();
}
function dynamicControllerTemplate() {
    ob_start();
    include_once APP_FACTORY . 'dynamic.txt';
    return ob_get_clean();
}
function getControllerTemplate() {
    ob_start();
    include_once APP_FACTORY . 'get.txt';
    return ob_get_clean();
}
function postControllerTemplate() {
    ob_start();
    include_once APP_FACTORY . 'post.txt';
    return ob_get_clean();
}
function postajaxControllerTemplate($route) {
    $template = [ucfirst($route)];
    $markup = ['{{filename}}'];
    ob_start();
    include_once 'postajax.txt';
    return str_replace($markup, $template, ob_get_clean());
}
function getajaxControllerTemplate($route) {
    $template = [ucfirst($route)];
    $markup = ['{{filename}}'];
    ob_start();
    include_once 'getajax.txt';
    return str_replace($markup, $template, ob_get_clean());
}
main($options);
?>